all: lint test


# Check source for errors and style violations
lint:
	jg lint

.PHONY: lint


# Run unit-tests
test:
	@ for i in t/{1..9}*.sh; do \
		[ -x "$$i" ] || continue; \
		echo $$i; "$$i" || exit $?; \
	done

.PHONY: test


# Nuke artefacts generated by tests
clean:
	rm -rf t/tmp/*
